from time import sleep
from selenium.webdriver import Chrome, ChromeOptions
from selenium.webdriver.common.by import By
o = ChromeOptions()
o.add_experimental_option("detach", True)
driver = Chrome(options=o)
driver.get('https://the-internet.herokuapp.com/')
driver.maximize_window()
sleep(2)
driver.find_element(By.LINK_TEXT,"JavaScript Alerts").click()
sleep(2)
driver.find_element(By.XPATH,"//button[text()='Click for JS Alert']").click()
sleep(2)
alert=driver.switch_to.alert
print(alert.text)
alert.accept()
sleep(2)
driver.find_element(By.XPATH,"//button[text()='Click for JS Alert']").click()
sleep(2)
print(alert.text)
alert.accept()
sleep(2)
driver.find_element(By.XPATH,"//button[text()='Click for JS Prompt']").click()
sleep(2)
alert.send_keys("akshita")
print(alert.text)
alert.accept()
sleep(2)
driver.close()