from time import sleep

from selenium.webdriver import Chrome,ChromeOptions
o=ChromeOptions()
o.add_experimental_option("detach", True)
driver = Chrome(options=o)
driver.get('https://www.amazon.in/')
driver.maximize_window()
sleep(2)
driver.switch_to.new_window('tab')
driver.get('https://www.flipkart.com/')
sleep(2)
driver.switch_to.new_window('tab')
driver.get('https://www.myntra.com/')
print('Last tab :')
print(driver.title)
print(driver.current_url)
print('second tab :')
driver.switch_to.window(driver.window_handles[1])
print(driver.title)
print(driver.current_url)
print('First tab :')
driver.switch_to.window(driver.window_handles[0])
print(driver.title)
print(driver.current_url)
driver.switch_to.window(driver.window_handles[2])
driver.close()
driver.switch_to.window(driver.window_handles[1])
driver.close()
sleep(2)