from time import sleep
from selenium.webdriver import Chrome, ChromeOptions
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

o = ChromeOptions()
o.add_experimental_option("detach", True)
driver = Chrome(options=o)
driver.get("https://www.flipkart.com/")
driver.maximize_window()
sleep(2)
driver.implicitly_wait(10)
driver.find_element(By.XPATH,"//span[@class='b3wTlE']").click()
myntra=driver.find_element(By.XPATH,"//a[text()='Myntra']")
actions = ActionChains(driver)
actions.move_to_element(myntra).pause(2).click(myntra).perform()
cleartrip=driver.find_element(By.XPATH,"//a[text()='Cleartrip']")
actions.move_to_element(cleartrip).click(cleartrip).perform()
Shopsy=driver.find_element(By.XPATH,"//a[text()='Shopsy']")
actions.move_to_element(Shopsy).click(Shopsy).perform()
print('list of ID of all Tabs: \n' , driver.window_handles)
print("\n First Tab:")
print('Title:',driver.title)
print('URL:',driver.current_url)
print('ID:',driver.current_window_handle)
driver.switch_to.window(driver.window_handles[1])
print('\n Second Tab:')
print('Title:',driver.title)
print('URL:',driver.current_url)
print('ID:',driver.current_window_handle)
driver.switch_to.window(driver.window_handles[2])
print('\n Third Tab:')
print('Title:',driver.title)
print('URL:',driver.current_url)
print('ID:',driver.current_window_handle)
driver.switch_to.window(driver.window_handles[3])
print('\n Fourth Tab:')
print('Title:',driver.title)
print('URL:',driver.current_url)
print('ID:',driver.current_window_handle)
sleep(2)
driver.quit()

